# Generated by Django 4.2 on 2023-04-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_details', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25, unique=True)),
                ('contacts', models.ManyToManyField(to='contact_details.contact_det')),
            ],
        ),
    ]
