# Generated by Django 4.2 on 2023-04-30 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact_details', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payable_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('days_attended', models.IntegerField()),
                ('days_present', models.IntegerField()),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contact_details.contact_det')),
            ],
        ),
    ]
