# Generated by Django 4.2 on 2023-04-30 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_details', '0003_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='days_present',
            new_name='total_days',
        ),
    ]
